### ISSUE TITLE
Model Checkpoints Request

### ISSUE THREAD

**Issue by nGQD** [resuldagdanov/DeFIX#11]
Hello, can you kindly share the trained model checkpoints used in DeFIX? Thanks in advance!

**Comment by resuldagdanov** [comment]
Hello,

We appreciate your interest and engagement with our project.

Regrettably, during the paper review process, we encountered an unforeseen issue. All of the collected datasets and trained model checkpoints were inadvertently deleted from our workstation. :(

However, we want to assure you that you can still collect the dataset using our provided codes, and the model training process remains applicable.

Thank you for your understanding.
Best wishes,
Resul
