### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by HappyJayLiu** [resuldagdanov/DeFIX#12]
Can you provide detailed instructions on how to configure the environment?

**Comment by resuldagdanov** [comment]
Hello Doraemonprogrammer,

Steps to follow:

1. First, you will need to collect a dataset by running Carla Autopilot.
2. You can train our proposed imitation learning models with the collected dataset.
3. Then evaluate the trained model.
4. Find the failure location by analysing the evaluation performance.
5. Train a reinforcement learning agent on this identified failure location.
6. Train a model selection neural network to select which trained agent to run in parallel.

For imitation learning and data collection steps, you can follow the following:
https://github.com/resuldagdanov/scenario-based-rl/tree/imitation_learning
