### ISSUE TITLE
Provision Steps

### ISSUE THREAD

**Issue by HappyJayLiu** [resuldagdanov/DeFIX#13]
move 'resnet50' file to directory: <DeFIX_PATH/checkpoint/models/>

What should I do？
Where is the resnet50 located?  Where is the <DeFIX_PATH/checkpoint/models/> located?

**Comment by resuldagdanov** [comment]
Hi Doraemonprogrammer,

1. The Resnet model could be downloaded from the following link:
https://pytorch.org/vision/stable/models.html

Please follow an example in the link.

2. DeFIX_PATH is a path where the repository is located on your PC.

3. Create a folder /checkpoint/models/ in the repository and store all models there.
